import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 * Graphical User Interface
 * 
 * @author Vance Field
 * @version 5-Apr-2016
 */
public class GUI {
    
    OutputWindow ow = new OutputWindow();
    Thread t;
    private JPanel panel;
    private JTextField console;
    private JButton read, browse;
    private JFileChooser chooser;
    public File[] files = new File[10];
    
    /**
     * Constructor
     */
    public GUI(){
        initComponents();
    }
    
    /**
     * Initializes the components of the gui
     */
    private void initComponents(){
        // panel
        panel = new JPanel();        
        
        // console
        console = new JTextField("Click Browse and select the file(s) you wish "
                + "to read.");
        console.setPreferredSize(new Dimension(300,50));
        console.setEditable(false);
        Font font = new Font("Courier",Font.BOLD,10);
        console.setFont(font);
        
        // browse button
        browse = new JButton("Browse");        
        browse.addActionListener(new ActionListener() {
           public void actionPerformed(ActionEvent e){
               chooser = new JFileChooser();
               chooser.setMultiSelectionEnabled(true); 
               int returnVal = chooser.showOpenDialog(null);
               if(returnVal == JFileChooser.APPROVE_OPTION){
                   try {
                       files = chooser.getSelectedFiles();
                       console.setText("Click Read to display the contents of "
                               + "the selected text file(s).");
                   } catch(Exception er){
                       System.out.println("Could not add selected file(s).");
                       er.printStackTrace();
                   }                       
               }               
           } 
        });
        
        // open button
        read = new JButton("Read");
        read.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e){
               //System.out.println("read clicked.");                 
                for(int i = 0; i < files.length; i++){
                    try {
                        t = new Thread(new Reader(
                                files[i].getPath(),files[i].getName(),i));
                        //System.out.println("Thread created.");
                        t.start();
                        //System.out.println("Thread started.");                     
                        
                        console.setText("Successfully read text file(s)."
                                + " You may select more files.");
                        
                    // autogenerated catch clause by netbeans
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(GUI.class.getName()).
                                log(Level.SEVERE, null, ex);
                    }
                }
                
            }
        });       
        
        // add components
        panel.add(console);
        panel.add(browse);
        panel.add(read);
    }
    
    /**
     * Creates and displays the main frame
     */
    public void display(){
        JFrame frame = new JFrame("Vance Field");
        frame.setSize(380,120);
        frame.setLocationRelativeTo(null);
        frame.setResizable(false);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setContentPane(panel);
        frame.setVisible(true);
    }   
    
} // class gui